### ISSUE TITLE
Add getting started instructions

### ISSUE THREAD

**Issue by jackiekazil** [Corvince/mesa-geo#1]
Hey! Really excited about this! Can you add 'getting started' instructions to the Read me for folks that want to play around with it.  :-)

**Comment by jackiekazil** [comment]
I have never seen someone so happy about a ticket! hahahahah

**Comment by jackiekazil** [comment]
Looks good. Can you add an "Install / setup" section?

**Comment by Corvince** [comment]
Haha, well it is my first public repository and an issue shows that someone is interested. I think that is a good thing!

I am not sure of the best way of installing. I would recommend cloning this repo and then install it using `pip install -e .`
Is this something I should recommend or do you know any better solution? (in general)
