### ISSUE TITLE
idx_id not set when adding agents.

### ISSUE THREAD

**Issue by bpmweel** [Corvince/mesa-geo#14]
Hi,

When adding agents to the index, no matter which way, the add function does not set the idx_id on the agent, which means that the delete function does not work:

```
File "/Users/bweel/Software/projects/dynaslum/residential-choice-model/rcm/model/model.py", line 168, in remove_location
    self.grid.remove_agent(agent)
  File "/usr/local/lib/python3.6/site-packages/mesa_geo/geospace.py", line 67, in remove_agent
    self.idx.delete(agent.idx_id, agent.shape.bounds)
AttributeError: 'SlumLocationAgent' object has no attribute 'idx_id'
```

**Comment by Corvince** [comment]
Thanks for reporting, Not sure why I used `idx_id` at all, but the Rtree should be able to use the unique_id of the agents. I'll do the necessary changes

**Comment by bpmweel** [comment]
I'm not sure this solution will work in every case, because the unique_id of an agent can be anything, while rtree expects a long integer.

In my case my agents have a string as a unique id, which is loaded from a geojson file.

**Comment by Corvince** [comment]
Ah, probably `id(agent)` should be sufficient as an index integer, no?!

**Comment by bpmweel** [comment]
Yes I agree.

I took a look at `id(agent)` and the documentation says `This is an integer (or long integer) which is guaranteed to be unique and constant for this object during its lifetime` which fits quite well with the use in mesa-geo.

I also like it more than setting an `_idx_id` as a side-effect.

**Comment by Corvince** [comment]
Ok I tried using `id(agent)`. Could you please test it? I am still not able to run my own project atm 😜

**Comment by bpmweel** [comment]
It took me a while to get back to this, but I tested it today and it seems to work well for me. Thanks for the changes!

**Comment by Corvince** [comment]
Hah! I just remembered this issue today and wasn't sure if I ever fixed it. But glad I did and it worked ;)

Thanks for coming back to this.
