### ISSUE TITLE
Virus on network issue

### ISSUE THREAD

**Issue by Samakwa** [Corvince/mesa-geo#15]
Hi,
I'm trying to run Virus on Network Example.

When I execute the run.py, I get this error: 
AttributeError: module 'server' has no attribute 'launch'

There is no launch function on the server.py. 
Any idea on how to resolve this, please?

**Comment by Corvince** [comment]
Hey there, this is an issue with mesa and not mesa-geo. However, I re-ran the example on mesa and could not reproduce your issue. Could you re-check how you installed mesa and then open a new issue at mesa?
