### ISSUE TITLE
Syntax change in pyproj raising FutureWarning

### ISSUE THREAD

**Issue by majdal** [Corvince/mesa-geo#18]
First of all, nice work! This is a very exciting project :)

I was going through the tutorial, and I got the following warning: 

```
/Users/me/.local/share/virtualenvs/thesis-PKkYFUSX/lib/python3.6/site-packages/pyproj
/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:
<code>' is the preferred initialization method. When making the change, be mindful of axis order 
changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
```
Following the [link](https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6) in the warning, it's clear that there's a syntax change in pyproj. I dug through mesa-geo's code, and fixed the issue. I'm creating a pull request to go along.

**Comment by Corvince** [comment]
Thanks for the heads-up! I don't have much time currently to work in mesa-geo, but will try to review your PR and mostly merge it (judging from first look)
