### ISSUE TITLE
get_intersecting_agents doesn't seem to be implemented 

### ISSUE THREAD

**Issue by schierkolk** [Corvince/mesa-geo#2]
I was trying to run your GeoShelling example.  Everything pops up but fails when it tries the first step do to a lack of the get_intersecting_agents method in the GeoSpace object.

It is called in the examples/GeoSchelling/model.py 

The method is in the description for the GeoSpace object. 

https://github.com/Corvince/mesa-geo/search?utf8=%E2%9C%93&q=intersecting&type=

**Comment by Corvince** [comment]
Hey there,

very sorry for the late reply! Your issue slipped my eyes and I haven't been working on geo-mesa for a long time. 

I had reorganized the way shape interactions work and forgot to reimplement the get_intersecting_agents method. 

I have updated the repo just now and it should work now, even with a proper visualisation (that was broken before anyway).

Would love to hear back from you if its working now!
