### ISSUE TITLE
Support for non-GeoAgents in GeoSpace grid

### ISSUE THREAD

**Issue by glicerico** [Corvince/mesa-geo#21]
Can a GeoSpace grid contain agents that are not GeoAgents? If not, how do you recommend to include agents moving on a map? As "Point" GeoAgents?

**Comment by Corvince** [comment]
No, currently the GeoSpace does not allow non-GeoAgents (what would be the point in adding them to a GeoSpace if they have no coordinates?)

But yes, it sounds like you would want to use "Point" GeoAgents. Note however, that the visualization of points is currently broken (see #17 )

**Comment by glicerico** [comment]
I see, makes sense. Thanks!
I saw the workaround for the visualization problem, hope that works.
