### ISSUE TITLE
Mobility_range value

### ISSUE THREAD

**Issue by alessandro-pisano** [Corvince/mesa-geo#24]
Hi I have a question, regarding mesa-geo/examples/GeoSIR/model.py
Could you tell me what the mobility_range value represents? I understand it is a measure of how much the agent should move but I don't understand if the value is in meters, kilometres, miles...

Thank you!

**Comment by Corvince** [comment]
The unit depends on the coordinate reference system. The example uses the default "web mercator" projection, which uses meters. However, the example is more of a toy example and the actual value has not much of an actual meaning.
