### ISSUE TITLE
GeoSIR error: _recreate_rtree() missing 1 required positional argument: 'new_agents'

### ISSUE THREAD

**Issue by applibres** [Corvince/mesa-geo#25]
Dear GeoSIR friends:
I have tried to run GeoSIR project but I have two issues:
1) Firefox does not display neither map nor data
How can I configure my browser in order to display the map? 

2) Chromium displays the map and data, but when I tried to run the model, I get the next message:

ERROR:tornado.application:Uncaught exception GET /ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8521', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/lib/python3.7/site-packages/mesa_geo/visualization/ModularVisualization.py", line 199, in on_message
    self.application.model.step()
  File "/mesa-geo-master/examples/GeoSIR/model.py", line 217, in step
    self.grid._recreate_rtree()  # Recalculate spatial tree, because agents are moving
TypeError: _recreate_rtree() missing 1 required positional argument: 'new_agents'

Do you know how can I fix it?

My platform is LinuxUbuntu 18.04 and python 3.7 .

Thanks.

**Comment by Corvince** [comment]
GeoSIR requires the latest (unreleased) version of mesa_geo. Try to install from GitHub or clone the repo and install locally

**Comment by Corvince** [comment]
The latest version of mesa_geo fixed this issue
