### ISSUE TITLE
Error in extracting agents from GeoSpace.agents

### ISSUE THREAD

**Issue by giacrava** [Corvince/mesa-geo#26]
Hi! I'm following the README tutorial and I'm getting an error in the passage to extract the list of agents.

If I run the line `agent = m.grid.agents[0]` I get the TypeError "'dict_values' object is not subscriptable". I checked the module and, in fact, when I call the `agents` attribute I get a dict_values object. 
Shouldn't it be converted to a list in order to be indexable? To make it work I have to use `agent = list(m.grid.agents)[0]`.

Thanks!

**Comment by giacrava** [comment]
I just noticed that I incur in the same problem when I call the .get_neighbors method, since in the script it has the line 
`neighbors = [self.agents[i] for i in neighbors_idx]`

**Comment by giacrava** [comment]
I realized that the error appears only in Jupyter Notebook. 
In JN, if I run `type(m.grid.agents)` I get 'dict_values'.
In Spyder, I get 'list' and everything works fine (I'm in the same environment).

**Comment by Corvince** [comment]
Thanks for the bug report. I can confirm your error.

However, it seems that you have 2 versions installed, one from pypi and one from GitHub. The GitHub version contains the bug, but is unreleased. Using the version from pypi should solve your issue, but I will also fix the master version and make a new release. But just probably not within the next few weeks (will be on vacation)

**Comment by Corvince** [comment]
Just realized how simple the fix *should* be.  The master version should work again. Hopefully I can do a new release this evening (also to include the GeoSIR example properly)

**Comment by giacrava** [comment]
Perfect, thanks a lot!
