### ISSUE TITLE
Puzzling result when modifying GeoSIR example

### ISSUE THREAD

**Issue by NickGotts** [Corvince/mesa-geo#31]
I aim to use Mesa, and potentially Mesa-geo, to model virus transmission within a building (specifically, a hospital). So I tried substituting a geojson file derived from a polygon Shapefile representing the internal layout of a building, for the file of Toronto neighbourhoods. I attach the zipped file below (the building is a university building in Chicago, the Edward D Anderson Building, as I don't yet have the hospital floor plans). 

The model appears to run successfully, but the visualization does not work properly. A map appears, and I can zoom in on the building. No internal structure or agents show up - perhaps not surprising given the source of the "Leaflet" maps - but the steps counter does not appear, and the chart has the wrong Y-axis, and nothing appears on it as the model runs. I have (accidentally) discovered that running the original model within a Jupyter notebook, preceded by the command:
%matplotlib widget
reproduces the same faulty visualization.

I can't see any feature of the geojson file that differs in any obvious way from the original. Using a different alternative - a map of postal districts in part of London - does not cause the same problem. Using a geopandas GeoDataFrame, or the Shapefile itself, gives the same result as using the geojson file. Removing "map_element" from the list of visualization elements used to define "server" results in the steps counter and correct chart appearing.

Any ideas what is happening? Thanks.
Nick Gotts (n.gotts@leeds.ac.uk - new work email)

[Rooms2_fixed_4326.zip](https://github.com/Corvince/mesa-geo/files/5781406/Rooms2_fixed_4326.zip)

**Comment by NickGotts** [comment]
Clarification: I did of course change the MAP_COORDS and unique_id parameters appropriately.

**Comment by NickGotts** [comment]
OK, resolved (not by me). The problem appears to have been that some of the properties in my geojson file had the value null; changing them to "null" worked.

**Comment by Corvince** [comment]
Glad you got it working! Feel free to open more issues if you run into more issues
