### ISSUE TITLE
Import shapes from various formats

### ISSUE THREAD

**Issue by Corvince** [Corvince/mesa-geo#4]
Currently, one can import Agent from shapes if data is in the GeoJSON format. A more user-friendly way would be to support various file formats. Changing the internal GeoSpace representation to a GeoPandas GeoDataFrame we should be able to import most formats with a `.from_file()` function (passed directly to GeoPandas). Additionaly we should keep the `.from_GeoJSON()` (for example for accessing web ressources) and also include `.from_GDF()` (for direct import of GeoDataFrames).

Any more ideas/wishes for data formats?

> @ljwolf
> 1 .OK; I think that's pretty straight forward, then! I can help implement this as needed, but I do not have the same amount of time for this stuff now that the scipy sprints are over 😄

Thanks for offering help, but I guess I will implement the GeoPandas part myself and then there is nothing left to do on this issue ;)

**Comment by Corvince** [comment]
I added `create_agents_from_shapefile` as a convenience, which uses [PyShp](https://github.com/GeospatialPython/pyshp) to actually just transform the shapefile records to GeoJSON and then call `create_agents_from_GeoJSON`

I also patched `create_agents_from_GeoJSON` slightly, so GeoDataFrames can now be turned into agents simply by calling `create_agents_from_GeoJSON(gdf.to_json())` (and thus any format can easily be used if GeoPandas (i.e. fiona) can read it.)

**Comment by ljwolf** [comment]
That looks excellent, great job. I think that's sufficient for what people would want, but I'd definitely throw in a `create_agents_from_geodataframe` that wraps this up so a user knows that's the way to get inside.

**Comment by Corvince** [comment]
Yeah, thats probably a very good idea. That would be much clearer and more straightforward to support any file format.
