### ISSUE TITLE
You may need to import the visualization module in __init__.py

### ISSUE THREAD

**Issue by schierkolk** [Corvince/mesa-geo#7]
I was able to get the code to work. I had to add 

`from mesa_geo.visualization import *`
 To the main __init__.py

I also created a new __init__.py the visualization folder and added
`from .MapModule import *`
f`rom .ModularVisualization import *`

**Comment by Corvince** [comment]
Thanks for your feedback! Glad you managed to get it to work. 

Could you give some more context to when this is necessary? I just installed mesa-geo to a clean virtual environment and could run the GeoSchelling example without your modifications.

I would also love to hear your use-case and ideas for how to improve mesa-geo and its handling.

**Comment by Corvince** [comment]
Should be fixed now
